<?php

use Illuminate\Database\Seeder;

class BlogTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('blogs')->insert(['title' => 'And then you can', 'body' => 'yarn is much faster than npm so you can do yarn add font-awesome --save – avn Jan 26 at 9:11Once I had a problem with fontawesome. Tried all, downloaded, npm installed. but then found the problem frontend developer wrote a code in css *{} for every tag, and I deleted that code then fontawesome workd perfect', 'user_id' => '1']);
        DB::table('blogs')->insert(['title' => 'And then you can', 'body' => 'yarn is much faster than npm so you can do yarn add font-awesome --save – avn Jan 26 at 9:11Once I had a problem with fontawesome. Tried all, downloaded, npm installed. but then found the problem frontend developer wrote a code in css *{} for every tag, and I deleted that code then fontawesome workd perfect', 'user_id' => '1']);
        DB::table('blogs')->insert(['title' => 'And then you can', 'body' => 'yarn is much faster than npm so you can do yarn add font-awesome --save – avn Jan 26 at 9:11Once I had a problem with fontawesome. Tried all, downloaded, npm installed. but then found the problem frontend developer wrote a code in css *{} for every tag, and I deleted that code then fontawesome workd perfect', 'user_id' => '1']);
        DB::table('blogs')->insert(['title' => 'And then you can', 'body' => 'yarn is much faster than npm so you can do yarn add font-awesome --save – avn Jan 26 at 9:11Once I had a problem with fontawesome. Tried all, downloaded, npm installed. but then found the problem frontend developer wrote a code in css *{} for every tag, and I deleted that code then fontawesome workd perfect', 'user_id' => '1']);
        DB::table('blogs')->insert(['title' => 'And then you can', 'body' => 'yarn is much faster than npm so you can do yarn add font-awesome --save – avn Jan 26 at 9:11Once I had a problem with fontawesome. Tried all, downloaded, npm installed. but then found the problem frontend developer wrote a code in css *{} for every tag, and I deleted that code then fontawesome workd perfect', 'user_id' => '1']);
        DB::table('blogs')->insert(['title' => 'And then you can', 'body' => 'yarn is much faster than npm so you can do yarn add font-awesome --save – avn Jan 26 at 9:11Once I had a problem with fontawesome. Tried all, downloaded, npm installed. but then found the problem frontend developer wrote a code in css *{} for every tag, and I deleted that code then fontawesome workd perfect', 'user_id' => '1']);
        DB::table('blogs')->insert(['title' => 'And then you can', 'body' => 'yarn is much faster than npm so you can do yarn add font-awesome --save – avn Jan 26 at 9:11Once I had a problem with fontawesome. Tried all, downloaded, npm installed. but then found the problem frontend developer wrote a code in css *{} for every tag, and I deleted that code then fontawesome workd perfect', 'user_id' => '1']);
        DB::table('blogs')->insert(['title' => 'And then you can', 'body' => 'yarn is much faster than npm so you can do yarn add font-awesome --save – avn Jan 26 at 9:11Once I had a problem with fontawesome. Tried all, downloaded, npm installed. but then found the problem frontend developer wrote a code in css *{} for every tag, and I deleted that code then fontawesome workd perfect', 'user_id' => '1']);
        DB::table('blogs')->insert(['title' => 'And then you can', 'body' => 'yarn is much faster than npm so you can do yarn add font-awesome --save – avn Jan 26 at 9:11Once I had a problem with fontawesome. Tried all, downloaded, npm installed. but then found the problem frontend developer wrote a code in css *{} for every tag, and I deleted that code then fontawesome workd perfect', 'user_id' => '1']);
        DB::table('blogs')->insert(['title' => 'And then you can', 'body' => 'yarn is much faster than npm so you can do yarn add font-awesome --save – avn Jan 26 at 9:11Once I had a problem with fontawesome. Tried all, downloaded, npm installed. but then found the problem frontend developer wrote a code in css *{} for every tag, and I deleted that code then fontawesome workd perfect', 'user_id' => '1']);
        DB::table('blogs')->insert(['title' => 'And then you can', 'body' => 'yarn is much faster than npm so you can do yarn add font-awesome --save – avn Jan 26 at 9:11Once I had a problem with fontawesome. Tried all, downloaded, npm installed. but then found the problem frontend developer wrote a code in css *{} for every tag, and I deleted that code then fontawesome workd perfect', 'user_id' => '1']);
        DB::table('blogs')->insert(['title' => 'And then you can', 'body' => 'yarn is much faster than npm so you can do yarn add font-awesome --save – avn Jan 26 at 9:11Once I had a problem with fontawesome. Tried all, downloaded, npm installed. but then found the problem frontend developer wrote a code in css *{} for every tag, and I deleted that code then fontawesome workd perfect', 'user_id' => '1']);
        DB::table('blogs')->insert(['title' => 'And then you can', 'body' => 'yarn is much faster than npm so you can do yarn add font-awesome --save – avn Jan 26 at 9:11Once I had a problem with fontawesome. Tried all, downloaded, npm installed. but then found the problem frontend developer wrote a code in css *{} for every tag, and I deleted that code then fontawesome workd perfect', 'user_id' => '1']);
        DB::table('blogs')->insert(['title' => 'And then you can', 'body' => 'yarn is much faster than npm so you can do yarn add font-awesome --save – avn Jan 26 at 9:11Once I had a problem with fontawesome. Tried all, downloaded, npm installed. but then found the problem frontend developer wrote a code in css *{} for every tag, and I deleted that code then fontawesome workd perfect', 'user_id' => '1']);
        DB::table('blogs')->insert(['title' => 'And then you can', 'body' => 'yarn is much faster than npm so you can do yarn add font-awesome --save – avn Jan 26 at 9:11Once I had a problem with fontawesome. Tried all, downloaded, npm installed. but then found the problem frontend developer wrote a code in css *{} for every tag, and I deleted that code then fontawesome workd perfect', 'user_id' => '1']);
        DB::table('blogs')->insert(['title' => 'And then you can', 'body' => 'yarn is much faster than npm so you can do yarn add font-awesome --save – avn Jan 26 at 9:11Once I had a problem with fontawesome. Tried all, downloaded, npm installed. but then found the problem frontend developer wrote a code in css *{} for every tag, and I deleted that code then fontawesome workd perfect', 'user_id' => '1']);
        DB::table('blogs')->insert(['title' => 'And then you can', 'body' => 'yarn is much faster than npm so you can do yarn add font-awesome --save – avn Jan 26 at 9:11Once I had a problem with fontawesome. Tried all, downloaded, npm installed. but then found the problem frontend developer wrote a code in css *{} for every tag, and I deleted that code then fontawesome workd perfect', 'user_id' => '1']);
        DB::table('blogs')->insert(['title' => 'And then you can', 'body' => 'yarn is much faster than npm so you can do yarn add font-awesome --save – avn Jan 26 at 9:11Once I had a problem with fontawesome. Tried all, downloaded, npm installed. but then found the problem frontend developer wrote a code in css *{} for every tag, and I deleted that code then fontawesome workd perfect', 'user_id' => '1']);
        DB::table('blogs')->insert(['title' => 'And then you can', 'body' => 'yarn is much faster than npm so you can do yarn add font-awesome --save – avn Jan 26 at 9:11Once I had a problem with fontawesome. Tried all, downloaded, npm installed. but then found the problem frontend developer wrote a code in css *{} for every tag, and I deleted that code then fontawesome workd perfect', 'user_id' => '1']);
        DB::table('blogs')->insert(['title' => 'And then you can', 'body' => 'yarn is much faster than npm so you can do yarn add font-awesome --save – avn Jan 26 at 9:11Once I had a problem with fontawesome. Tried all, downloaded, npm installed. but then found the problem frontend developer wrote a code in css *{} for every tag, and I deleted that code then fontawesome workd perfect', 'user_id' => '1']);
        DB::table('blogs')->insert(['title' => 'And then you can', 'body' => 'yarn is much faster than npm so you can do yarn add font-awesome --save – avn Jan 26 at 9:11Once I had a problem with fontawesome. Tried all, downloaded, npm installed. but then found the problem frontend developer wrote a code in css *{} for every tag, and I deleted that code then fontawesome workd perfect', 'user_id' => '1']);
        DB::table('blogs')->insert(['title' => 'And then you can', 'body' => 'yarn is much faster than npm so you can do yarn add font-awesome --save – avn Jan 26 at 9:11Once I had a problem with fontawesome. Tried all, downloaded, npm installed. but then found the problem frontend developer wrote a code in css *{} for every tag, and I deleted that code then fontawesome workd perfect', 'user_id' => '1']);
        DB::table('blogs')->insert(['title' => 'And then you can', 'body' => 'yarn is much faster than npm so you can do yarn add font-awesome --save – avn Jan 26 at 9:11Once I had a problem with fontawesome. Tried all, downloaded, npm installed. but then found the problem frontend developer wrote a code in css *{} for every tag, and I deleted that code then fontawesome workd perfect', 'user_id' => '1']);
    }
}
